apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  org: umich
  project: qualtrics-lti
resources:
- web-autoscaler.yaml
- web-deployment.yaml
- web-service.yaml
- web-route.yaml
- web-volume.yaml
- build.yaml
namePrefix: qualtrics-lti-
configMapGenerator:
- name: qualtrics-lti
crds:  # Use CRDs to support OpenShift resource kinds
- openshift-buildconfig.json
- openshift-deploymentconfig.json
- openshift-route.json