apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: qualtrics-lti
  minReplicas: 1
  maxReplicas: 1 